### ISSUE TITLE
Add Stone to Event Poring drops & Change [Adept Adventurer] navi link in Quest UI window

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#100]
**Vicente Job Manual Steal Quest**
You're supposed to be able to steal "Stone" from the Porings in the room, but currently you are not able. After doing some digging (and with Trojal's help), it turns out that the damn things don't actually drop Stone!

So, add "Stone" to monster ID 1725 ([divine-pride](https://www.divine-pride.net/database/monster/1725). Search for 1725 in this file: https://raw.githubusercontent.com/TitanRO/server/stable/db/revo/mob_db.conf?token=AJEUol9kDqjwj4oiL_six8-0CCgCzIDwks5bGxDSwA%3D%3D.

**Adventurer's Companion Navi Link in Quest Window**
![adept_adventurer_quest_wrong_navi](https://user-images.githubusercontent.com/9508002/40866923-0c8b75b4-65c6-11e8-8b50-bd0af4d2e2e2.PNG)

That navi link to the [Adept Adventurer] takes you to some random spot on the South Prontera field. Instead it should take a player to iz_ac01,45,80.

**Comment by trojal** [comment]
Fixed Criatura Poring in https://github.com/TitanRO/server/commit/267d397392dffc231505ae8ab229e7e9583e204e
Fixed NAVI in https://github.com/TitanRO/client/commit/0bf50b7b803433dc4376dfc696607b73ccc33703
