### ISSUE TITLE
Mini party window bugs

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#101]
From discord: 
> if you open a mini-party window it bugs out and keeps reopening a chat with the person even if they quit party, go into different map, go offline, etc

**Comment by mlbpro417** [comment]
I'm curious if this behavior has anything to do with the lock/unlock button on the friends menu.  You can't remove them if the friend's list is locked, for example.  I have used that menu quite a lot so far without seeing this one, maybe I can try and reproduce it.

**Comment by trojal** [comment]
Will be fixed with next client release, nothing we can do for now.
