### ISSUE TITLE
Implement iRO aspd formula

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#11]
The iRO aspd formula is quite a bit faster than kRO but we have a lot of people coming from iRO..

**Comment by gielreijns** [comment]
Implemented in https://github.com/TitanRO/server/commit/576c4bf5e3c7dedac44d5e81b8fcf1bab0078a2b and https://github.com/TitanRO/server/commit/f113f71eb2ee46a132ba0da8a8d139a55a2b22d8
