### ISSUE TITLE
moc_fild03 portal bugged

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#111]
From discord:
> [8:16 PM] thechuckcharles: moc_fild03 is bugged
> [8:16 PM] thechuckcharles: the portal at the bottom of the map doesnt exist
> [8:16 PM] thechuckcharles: but u can go through the one the map below
> [8:17 PM] thechuckcharles: resulting in your going through and not being able to go back

**Comment by saegys** [comment]
https://github.com/TitanRO/server/commit/086694ec492eed1c8e903e8d6eef4be348ce104c
