### ISSUE TITLE
Add Assassin Guild Bar back to Morocc

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#125]
In order to finish the [Curse of Gaebolg quest](https://irowiki.org/wiki/Curse_of_Gaebolg_(Founding_of_the_Nation_Myth_Quest)), you have to go into the Assassin Guild Bar in Morroc (step #14). Unfortunately the warp doesn't exist!

![assassin_bar_morroc_warp_missing](https://user-images.githubusercontent.com/9508002/41263748-9c14c308-6dae-11e8-88e7-049f55c49c12.PNG)

Link to the classic version, which also mentions a "Sharp Looking Kid" NPC outside, who isn't there: https://irowiki.org/classic/Curse_of_Gaebolg_(Founding_of_the_Nation_Myth_Quest).

Went searching through the code, and this [txt file](https://github.com/TitanRO/server/blob/stable/npc/titan/morroc/quests_morocc_old.txt) seems to show it as being disabled. So maybe it's as simple as just uncommenting out that whole block of code?

**Comment by trojal** [comment]
fixed in https://github.com/TitanRO/server/commit/732b0585a61eccd0c887bc0b3fca1edda187c36b
