### ISSUE TITLE
Battleground String Updates

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#133]
https://github.com/TitanRO/server/blob/stable/npc/custom/hBG/bg_common.txt

311: I'm a knight from a far country called Maroll Kingdom. --> I'm a knight from a faraway country called Maroll Kingdom.
398: Protect our army! --> Protect your army!
418: To get aditional points, --> To get additional points,
558: His Majesty has declared to choose either me or --> His Majesty has declared he will choose either me or

**Comment by trojal** [comment]
https://github.com/TitanRO/server/commit/c23fe3422c200b50b0d15a93941b40be5f12e204
