### ISSUE TITLE
Update client navigation info

### ISSUE THREAD

**Issue by TwoLaid** [TitanRO/Issues#15]
It would be really helpful to have the actual monster spawns in the client's navigation files. Right now the spawns are all wrong

**Comment by TwoLaid** [comment]
apparently there is a Hercules plugin to do this for you! :) https://github.com/HerculesWS/StaffPlugins/tree/master/Haru/naviluagenerator

**Comment by njosefbeck** [comment]
Just re-iterating that this would be helpful, especially before launch. When I was doing the Criatura monster hunting quests, I had a hard time finding Hornet since navi wasn't accurate. Ended up having to go to irowiki restart db.

**Comment by trojal** [comment]
Fixed in https://github.com/TitanRO/client/commit/26f05a8f5b71f4518e494503e1370ab0e8c73464
