### ISSUE TITLE
Limited stat reset NPC

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#24]
I should be able to adapt an existing limited stat reset NPC I have to have a weekly cooldown and cost associated.

**Comment by trojal** [comment]
Something based off this mechanism which resets 1 point at a time: https://storage.googleapis.com/ragnarok-server/uv-ro/uv-ro-eAmod/npc/uv-ro/reallocator.txt

after talking I believe we came to 200k zeny per stat point -- max 5 stats, 1m zeny per week

**Comment by saegys** [comment]
https://github.com/TitanRO/server/commit/b6a3afada55708a6c5c6338311ce36ed187b89d2
