### ISSUE TITLE
Add level restrictions to hunting boards

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#26]
While there, also put the "take all" and "turn in all" at the first item in list.

**Comment by trojal** [comment]
Renewal level restrictions:
https://irowiki.org/wiki/Bounty_Board_Quests

Re:Start level restrictions:
https://docs.google.com/spreadsheets/d/1SstRIRxO_9GkQGnq_VERT8VcnDlZ6FQHbIgA1dGmrKM/edit#gid=0

**Comment by saegys** [comment]
https://github.com/TitanRO/server/commit/c229283ca24d3378add9c9180e871bcf69b786a6
