### ISSUE TITLE
HEAL is adding MATK

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#38]
Since we reverted heal to the old system, heal seems to be adding ~100-200 (based on MATK) additional to the heal amount.

**Comment by trojal** [comment]
Shiro Yusuke on forums said:
> I noticed the Heal skill seemed to follow the classic heal formula much more closely, but also still noticed variations in heal amounts. I took off all my gear and kept myself buffed with Bless and Gloria. I am base level 99 with 101 Int without a weapon and 51 Luck with gears and Gloria with maxed Meditatio.
>
>No Luck gear, Gloria or weapon = Solid 2717 (as in, the heal amount never changed)
>
>Luck gear worn with Gloria and no weapon = Solid 2731
>
>+5 Evil Bone Wand (Int+4 and MATK+110) equipped = variable heal between 2834 and 2902.

**Comment by timogasda** [comment]
I believe this can be easily fixed by changing the code in `skill.c` a few lines further:

```
#ifdef RENEWAL
	// MATK part of the RE heal formula [malufett]
	// Note: in this part matk bonuses from items or skills are not applied
	switch( skill_id ) {
		case BA_APPLEIDUN:
		case PR_SANCTUARY:
		case NPC_EVILLAND:
			break;
		default:
			hp += status->get_matk(src, 3);
	}
#endif // RENEWAL
```

The `default` case catches here for `AL_HEAL`, so probably adding it to the lists of skills that `break` should do the trick :)

**Comment by saegys** [comment]
https://github.com/TitanRO/server/commit/6e47758d744bb226ab5d75977d2b7a73bfa8bfea
