### ISSUE TITLE
Double MATK of all monsters

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#39]
This is a mob's atk2 value... maybe it's related to code around here: https://github.com/TitanRO/server/commit/b867f0de7504e570f9724b5127daac24a4c636bd

But after talking about it, this will only make 36 monsters have more MATK than they had in Re:Start, which was using the wrong numbers for MATK.

**Comment by trojal** [comment]
Added in https://github.com/TitanRO/server/commit/d993923055939bb3e7e18d949b988d9691952c33, needs testing.

**Comment by mlbpro417** [comment]
KK does insane damage on the highest end, Osiris doing expected damage on the lower end.  Will probably need to tweak her when bio is close to release.

**Comment by trojal** [comment]
After discussing and giving some examples, we'll just buff Anubis to Re:Start level and leave the rest with reasonable MATK values

**Comment by trojal** [comment]
Fixed in https://github.com/TitanRO/server/commit/5f6077fdd015c17f0568c6274be1db8a0b9d3425
