### ISSUE TITLE
Izlude Captain Carocc

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#40]
https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L378

When you first start your character and are on the island, the int_land [Captain Carocc](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L178) gives you base EXP that lets you reach base 12. Then, if you do the int_land [Sailor](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L119)'s quest you end up at base 15, job 2.

Once you leave the island, the [Izlude Captain Carocc](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L378) will not give you the Hun quest, as he expects you to not only be a Novice, but also to be [below base level 15](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L381).

So, to activate this quest line, either the level requirement needs to be taken off, or the amount of EXP that int_land Captain Carocc and Sailor give needs to be lowered so that a new player won't be above base level 15 when they leave the island.

**Comment by trojal** [comment]
Limited the levels a player can gain by disabling multi level up: https://github.com/TitanRO/server/commit/3703880f9dd735012a6011d0855d7787b6c3561f
