### ISSUE TITLE
Criatura Academy Staff NPC (Hun)

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#41]
https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L803

Basically same issue as described in the [Captain Carocc](https://github.com/TitanRO/Issues/issues/40) issue, where this NPC requires you to be [below base 15](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L812) and a Novice in order to do his quest.

Proposed Solution: Remove the base 15 level requirement

**Comment by trojal** [comment]
This might be resolved by https://github.com/TitanRO/server/commit/3703880f9dd735012a6011d0855d7787b6c3561f (remove multi level up)
