### ISSUE TITLE
Information Staff NPC

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#42]
https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L1123

Same issue as reported in Captain Carocc Issue as well as Criatura Academy Staff NPC (Hun) issue (i.e. the [lvl 15 requirement](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L1132)).

Same solution too! Remove the lvl 15 requirement.

**Comment by trojal** [comment]
This might be resolved by https://github.com/TitanRO/server/commit/3703880f9dd735012a6011d0855d7787b6c3561f (remove multi level up)
