### ISSUE TITLE
Novice Combination Book & Kit

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#43]
The Novice Combination Book used to be readable, but now is just gibberish:

![novice_combination_book](https://user-images.githubusercontent.com/9508002/40131355-5d5294b0-58ff-11e8-879b-a4e1b53381d7.PNG)

**Additionally**, the Combination Kit seems to do nothing, even when one has the necessary recipe ingredients in their Inventory.

**Comment by trojal** [comment]
We can't fix the Combination Kit quickly, it requires adding a bunch of new code to craft these items. I'd say we should remove whichever NPC gives the Combination Kit and Book; incidentally it also means people can't get more tames for the Little Porings...

**Comment by njosefbeck** [comment]
So, the **Therapist** NPC gives the Book and Kits as part of their quest reward (line [here](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L2220)). So for that NPC, I would just remove those items from the items that it gives as rewards (this will be edited anyway when the kafra tickets are added).

**[General Store Owner](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L4420)** can be disabled completely though.

And yeah, the only issue I have with not being able to do the Kit/Book is that people won't be able to get more tames for the Little Porings. And if they can't tame a Little Poring, then they miss out on some quest EXP and rewards.

[The recipe](http://ragnarok.wikia.com/wiki/Novice_Combination_Book) is just 1 Green Herb + 1 Apple. Maybe a simple NPC could be put in place of the General Store Owner, that checks if you're a Novice Class, and then accepts those two items, and gives you 1 Unripe Apple for it.

If that's too much, then you could take the quest [rewards](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L5292) that the Friendly Poring gives players and put them somewhere else.

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/912af852e7a6849363e726cd446e4670b49fc3e0

Added an npc to sell the unripe apple at the same location as the General Store Owner

**Comment by njosefbeck** [comment]
Just to be sure, the NPC sells the Little Unripe Apple right? It's not the normal one, so just thought I'd make sure.

This is what the Friendly Poring gives:
```getitem(Unripe_Apple2, 5);```

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/86511570b83f25b329b14fb51dcb01d9e4df8922
