### ISSUE TITLE
Permanent "News" in Quest UI is unreadable

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#44]
![new_novice_quest](https://user-images.githubusercontent.com/9508002/40131435-99543d56-58ff-11e8-940c-2fb76382cdf9.PNG)

I'm not sure what this is supposed to say - seems to be referencing the Criatura Academy. It's also categorized as "News" in the Quest UI. Is there a way to either delete this, translate it, or change the text to be something useful for our server?

**Comment by trojal** [comment]
Need to replace with https://github.com/zackdreaver/ROenglishRE/blob/master/System/RecommendedQuestInfoList.lub

**Comment by trojal** [comment]
Fixed in https://github.com/TitanRO/client/commit/7789f831c1501eb97e2565ec36741558bd9eac60
