### ISSUE TITLE
Dacquoise NPC & Cooking

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#45]
https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L3891

Will we have the Cooking System implemented from the start of the server? According to my research, it wasn't added until [Episode 10.3 Noghalt](http://wiki.titanro.net/view/Episode_Timeline#Episode_10.3_Noghalt). I'm fine if it's in, but just making you all aware.

If we don't want cooking in at the start, then I think Dacquoise, Mille Feuille (line 6294), and Eclaire (line 6282) should be disabled until then.

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/d9360cf0bb65337bcc053986cb64ddcb13d327f1
https://github.com/TitanRO/server/commit/2b08747e2efc1cc747014e3d48891cce1eb19491
