### ISSUE TITLE
Attribute Expert - Crashed Client

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#46]
https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L3681

The Attribute Expert in the Criatura Academy crashed my client. I think I've seen this issue reference on the forums, but thought I would put it here as well. 

I've included the crash log:
[criatura_wizard_game_crash_log.txt](https://github.com/TitanRO/Issues/files/2010123/criatura_wizard_game_crash_log.txt)

**Comment by trojal** [comment]
Fixed in https://github.com/TitanRO/server/commit/4426d07f1b47b0d98709e67520a38d29a0096924
