### ISSUE TITLE
Enchanter Mounds & Enchanter Almond J NPCs

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#47]
Though I like the rewards one ultimately gets from these NPCs, especially for starting out characters, i.e.:
- Cotton Shirt [1] with SP+50, HP+100
- 1 Free Ticket for Kafra Storage
- Base and Job EXP (if Novice)

Since we won't have either Socket Enchant or Hidden Enchant on the server for launch, these NPCs should probably be disabled? They also reference other NPCs that won't exist (Leyablem, Seyablem), and places that won't be accessible (Maladongo - or however it's spelled).

**Comment by mlbpro417** [comment]
I would use those enchants on monk otherwise /gg

https://github.com/TitanRO/server/commit/28cafc575210b591b4520eab3de8d0f43f30a13d
