### ISSUE TITLE
Criatura Academy & Izlude Quests Rewards

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#48]
I've heard a couple users mention about the lack of Kafra tickets given for completing all of the Criatura and Izlude quests. Here's a list of all that one gets, as of the writing of this issue:

- Base and Job EXP that will get you somewhere around base level 28, job level 10
- Play Dead Skill
- First Aid Skill
- 380 Novice Potion
- 70 Novice Fly Wing
- 20 Novice Butterfly Wing
- Tattered Novice Ninja Suit, Somber Novice Hood, Novice Slippers, Novice False Eggshell, Novice Main-Gauche, Novice Guard
- Criatura Hat
- Criatura Hair Coupon
- 1 Novice Combination Book (unreadable)
- 10 Combination Kits (un-usable)
- 1 Red Herb
- 11 Apple
- 5 Free Ticket for Kafra Storage
- Baby Poring Egg (if can catch one)
- 3 Apple Juice (if can catch baby poring)
- 1 Pet Incubator (if can catch baby poring)
- +1 Level 1 Weapon (user decides)

The only Kafra tickets that you currently get are 5 for storage. Would be nice to add x number of Free Ticket for Kafra Teleport to the NPCs as well, especially since the amount currently is so low when compared to RE:Start.

Edited: removed those rewards that aren't in any longer due to disabled NPCs

**Comment by njosefbeck** [comment]
Based on iRO RE:Start, which gives 20 Free Ticket for Kafra Storage, and 30 Free Ticket for Kafra Transportation, I suggest that the following NPCs get tickets added in the amounts listed:

**[Criatura Academy Staff/Hun](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L803)**: 2 Storage, 2 Transportation
**[Information Staff](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L1122)**: 1 Storage, 2 Transportation
**[Therapist](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L2075)**: 2 Storage, 4 Transportation
**[Battle Instructor](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L4520)**: 5 Storage, 4 Transportation
**[Trainer Mainz](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L2803)**: 1 Storage, 4 Transportation
**[Attribute Expert](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L3680)**: 2 Storage, 5 Transportation
**[Shop Helper](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L3465)**: 2 Storage, 4 Transportation
**[Refinery Owner Han](https://github.com/TitanRO/server/blob/447725f46f5d38b32fea2a27af5495f6942cea64/npc/titan/re_jobs_academy.txt#L12545)** 5 Storage, 5 Transportation

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/19b250e98ac1aa9b6fbd882f4ee7968de7ef0a89

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/6a1d366bbe4abd5eea78ad92288b50ac22230aeb
