### ISSUE TITLE
Homunculus causing errors

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#49]
I know this is probably low priority, but when I went to log into my alchemist (who has a homun), I kept getting the following error (and had to force quit). Could be something with how the updated kRO client changed how Homunculus work (moving around AI files maybe)? I remember seeing that as a very recent update to official kRO... not sure if that could be affecting things in our client as well, or if it's another issue.

![homunculus_error](https://user-images.githubusercontent.com/9508002/40133224-b998d248-5904-11e8-815e-08256567991d.PNG)

**Comment by trojal** [comment]
Completed a while back with some client updates for Homunculus support.
