### ISSUE TITLE
Character creation cut-off text

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#50]
This is potentially minor, but thought I'd flag as something that would be nice to fix. The character name field doesn't seem to be tall enough and thus cuts off the bottom of my text!

![cut_off_text](https://user-images.githubusercontent.com/9508002/40133271-e05543d0-5904-11e8-8852-a1d2f5681d6c.PNG)

**Comment by trojal** [comment]
Fixed in next client update.
