### ISSUE TITLE
Disable Expanded Criatura Job Change NPCs & Update Academy Receptionist NPC

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#51]
The following Criatura NPCs are associated with/are the Job Change NPC for a class that's not on our server yet. They should be disabled. (Also remember that all these NPCs are duplicated across the different 'versions' of Izlude.)

**Gunslinger**
- [Lusa](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L7283)
- [[Gunslinger Classroom](https://github.com/TitanRO/server/blob/stable/npc/titan/re_jobs_academy.txt#L6682)]
- [Lusa's Desk](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L8034)
- [Quite Trainee](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L6425)
- [Noisy Trainee](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L6385)
- [Frightened Trainee](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L6465)
- [Guild Staff](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L8186)

**Taekwon**
- [Arang](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L8356)
- [[Taekwon Classroom](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L6676)]

**Ninja**
- [Ninja Guide](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L12317)
- [[Ninja Classroom](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L6658)]

**Academy Receptionist**
Comment out the following lines:
- [2752](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L2752), 2753, 2754

**Comment by mlbpro417** [comment]
Completed.

https://github.com/TitanRO/server/commit/ebeb192be7db8e44d3e5b53a992361f844cd3fe9
