### ISSUE TITLE
Criatura Cream Puff NPC

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#52]
This NPC handles the personality test, which recommends your first job. Since the NPC can recommend an Expanded class, and potentially try to warp you to that job's Criatura NPC, it needs to be altered to not do that. Maybe if the player would have gotten "Taekwon" it could just suggest "Archer" instead? Or something like that.

[Line where Cream Puff NPC dialogue starts](https://github.com/TitanRO/server/blob/81d835da91cab7819b4e42890ffcbee053c26c45/npc/titan/re_jobs_academy.txt#L6709)

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/e1fbf608bec82ce88ea8a67fa791d4143b88cf74
