### ISSUE TITLE
Reduce asura SP block

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#53]
Reduce block from 10s to 3s.

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/d9c14c5b4485f9e38ca59aa18dc78674ea4a6403

I think this covers both regular asura cases and also ones casted from a combo/root.  I wanna test it though.

**Comment by trojal** [comment]
Done in https://github.com/TitanRO/server/commit/d2baa46377b4e82848fec63af910b72347093726
