### ISSUE TITLE
Salim Hamid (Criatura Merchant Class NPC) never wants to talk to me!

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#55]
Salid Hamid is a real grump, and has never wanted to talk to my character. So I went digging [here](https://github.com/TitanRO/server/blob/4e3fec356b49c6191113d153752841dbd8f58393/npc/titan/re_jobs_academy.txt#L9636), and I think I found the reason why.

On line [9643](https://github.com/TitanRO/server/blob/4e3fec356b49c6191113d153752841dbd8f58393/npc/titan/re_jobs_academy.txt#L9643), if your character is either not a novice or is higher than BaseLevel 15, then he just defaults to not really talking to you. Though I haven't verified 100%, it seems like the other First Job NPCs only have a requirement that the character be a novice, and not a level requirement like that as well.

So maybe his BaseLevel 15 thing should be removed? Just a thought!

**Comment by trojal** [comment]
Removed baselevel check in https://github.com/TitanRO/server/commit/34202389f4e709e68aeca6697a106ff5ef1b2bf5
