### ISSUE TITLE
Disable Nightmare Pyramids NPC in moc_pyrdb1

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#59]
Remove the NPC for this quest: https://irowiki.org/wiki/Nightmare_Pyramids

Shouldn't be in the game yet, and apparently as of now just takes your money and doesn't warp you anywhere.

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/server/commit/fcac1d662b4befed1aa40091d49b599b5d56f5b3
