### ISSUE TITLE
Change skill "Absorp Spirits" to "Absorb Spirits"

### ISSUE THREAD

**Issue by njosefbeck** [TitanRO/Issues#60]
Probably shows up in the more than this file, but here's one: https://github.com/TitanRO/client/blob/master/GRF/TitanRO%20-%20tdata/data/luafiles514/lua%20files/skillinfoz/skilldescript.lub

Probably also here: https://github.com/TitanRO/client/blob/master/GRF/TitanRO%20-%20tdata/data/luafiles514/lua%20files/skillinfoz/skillinfolist.lub

**Comment by mlbpro417** [comment]
https://github.com/TitanRO/client/commit/d10fd417747ba9e28e0710165693037e9530f926
https://github.com/TitanRO/client/commit/3d6516ab277ddd8b2cd7661624394fa13a236f58
