### ISSUE TITLE
Client thinks weight limit starts at 50%

### ISSUE THREAD

**Issue by saegys** [TitanRO/Issues#69]
Shows the "Your weight limit is over 50, HP and SP will not recover naturally." and colors the weight red in Basic Info.

**Comment by trojal** [comment]
https://github.com/rathena/rathena/commit/b409936f8dbff237608776f7320098e1d556c458 contains some pointers for the packet to support this

**Comment by trojal** [comment]
Done https://github.com/TitanRO/server/commit/cfa092f9ba0257e5c61785eff74d3e919d5ac94d
