### ISSUE TITLE
Traps are piercing plants

### ISSUE THREAD

**Issue by trojal** [TitanRO/Issues#72]
Traps are dealing piercing damage to plants. Are they supposed to? Probably not. Did they before I fixed traps? Maybe.

**Comment by saegys** [comment]
Verified on RE:Start that they're not supposed to deal more than 1 damage.

**Comment by trojal** [comment]
Updated in https://github.com/TitanRO/server/commit/ec5ebecedcbb540a6441ca3e4e18fdb11814d9af
Though it was coded intentionally that traps should pierce plant def, I don't like it anyways.
