### ISSUE TITLE
@whosells not available to players

### ISSUE THREAD

**Issue by Liffeon** [TitanRO/Issues#73]
http://forum.titanro.net/index.php?/topic/85-server-info/
Listed as a command in the server info but is not usable in-game and doesn't appear in the @commands list.
![image](https://user-images.githubusercontent.com/18753527/40374340-c2eba2cc-5de0-11e8-9306-7a8babaf1de6.png)

**Comment by trojal** [comment]
Note to devs: There's a src/plugins/whosell.c but it's not enabled and users on Hercules forums reported that it doesn't work. Probably there's some basic code to re-use, but update some other parts of it.

**Comment by charlielovesu** [comment]
If you guys can add, consider adding "whonpcsells" as its a nice quality of life feature that allows you to look up where to find stuff from NPC. OriginsRO had it and it was convenient.

**Comment by trojal** [comment]
Added in https://github.com/TitanRO/server/commit/8c281fe383fc288d442e770c70f4bfc57bb7a0f5
