### ISSUE TITLE
Awakening and Concentration Pots give the same ASPD

### ISSUE THREAD

**Issue by timogasda** [TitanRO/Issues#84]
I have a 60+ Rogue with 50+4 AGI. Without and buffs and pots I have 170 ASPD. Consuming a Concentration Potion OR Awakening Potion boosts it to 174. So the Awa doesnt have any advantage over the Concentration pot.

Is that intended?

**Comment by saegys** [comment]
https://github.com/TitanRO/server/commit/df1278ab4b1dd55167f33f9b254275bf9f7e2735
